In [1]:
import pandas as pd

In [3]:
df_gastos= pd.read_csv("datos\DatosFinales\gastos.csv")
df_ingresos= pd.read_csv("datos\DatosFinales\ingresos.csv")

In [7]:
df_gastos["año"].unique()

array([2020, 2019, 2018, 2016, 2017, 2015, 2014, 2010, 2011, 2013, 2012])

In [15]:
len(df_gastos["ncodi"].unique())

857

In [4]:
df_gastos

,año,ncodi,totalcompra,producfarma,materialsani,implantes,restomateriasani,servcontratado,trabajocontratado,xrestocompras,...,xrestoserviexter,gastopersonal,sueldos,indemnizacion,segsocempresa,otrgassocial,dotaamortizacion,perdidadeterioro,xrestogasto,totcompragasto
0,2020,113.0,1535894,344330.0,169443,0.0,169443.0,1877.0,678201.0,342043.0,...,506018.0,26209836,19875799,349499.0,5984538,0.0,298707.0,-6504.0,50165.0,28810972
1,2020,619.0,7884157,971762.0,1749006,493444.0,1255562.0,3800207.0,1248674.0,114508.0,...,2635675.0,7083969,5203283,151380.0,1591074,138232.0,2423752.0,0.0,312984.0,20573925
2,2020,163.0,5453290,126493.0,1412366,574127.0,838239.0,3217684.0,647852.0,48895.0,...,882274.0,2890388,2180177,-402.0,663398,47215.0,202688.0,-54028.0,232471.0,9677715
3,2020,131.0,245802,72318.0,52506,0.0,52506.0,1114.0,24303.0,95561.0,...,487053.0,1887375,1437421,9506.0,416398,24050.0,12084.0,240.0,132044.0,2844476
4,2020,375.0,762218,114702.0,106844,60.0,106784.0,14526.0,188463.0,337683.0,...,192132.0,7764302,5838470,0.0,1837175,88657.0,184413.0,93708.0,1552.0,9037657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8445,2012,970.0,271324,8510.0,166422,0.0,166422.0,0.0,96392.0,0.0,...,90752.0,1010376,796935,0.0,213441,0.0,104331.0,0.0,63796.0,1945741
8446,2012,1019.0,1687968,126665.0,94290,0.0,94290.0,1080335.0,300411.0,86267.0,...,54771.0,2447989,1852771,0.0,590887,4331.0,132364.0,0.0,0.0,4493647
8447,2012,1016.0,5418532,336983.0,1152639,145404.0,1007235.0,2739305.0,1126019.0,63586.0,...,1360669.0,2624854,2066623,0.0,545427,12804.0,32691.0,99382.0,199998.0,10166669
8448,2012,1047.0,15537164,5516672.0,5255744,565150.0,4690594.0,0.0,3287539.0,1477209.0,...,4808689.0,43164526,34899381,0.0,8056716,208429.0,3297451.0,0.0,0.0,68948001
8449,2012,635.0,14508459,6275019.0,4311556,231481.0,4080075.0,0.0,3244840.0,677044.0,...,2108452.0,38113657,30888193,0.0,7040348,185116.0,1025569.0,0.0,150643.0,56338842

In [8]:
df_ingresos["año"].unique()

array([2013, 2014, 2015, 2012, 2017, 2010, 2019, 2021, 2020, 2018, 2011,
       2016])

In [10]:
len(df_ingresos["ncodi"].unique())

2424

In [13]:
df_ingresos.duplicated().sum()

np.int64(0)

In [20]:
df_ingresos["tipo"].unique()

array(['Hospital', 'consulExter', 'CMA', 'hospDia', 'Urgencia', 'hospDom'],
      dtype=object)

In [ ]:
df_ingresos["ncodi"].str.replace(",",".")

In [18]:
df_ingresos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55326 entries, 0 to 55325
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               55326 non-null  int64
 1   particulares             53952 non-null  float64
 2   aseguradoras             55322 non-null  float64
 3   aseguradoras_enfermedad  53952 non-null  float64
 4   aseguradoreas_trafico    53859 non-null  float64
 5   mutuas                   53942 non-null  float64
 6   tipo                     55326 non-null  object
 7   año                      55326 non-null  int64
 8   ncodi                    55308 non-null  object
dtypes: float64(5), int64(2), object(2)
memory usage: 3.8+ MB

In [19]:
df_ingresos.sample(10)

,Unnamed: 0,particulares,aseguradoras,aseguradoras_enfermedad,aseguradoreas_trafico,mutuas,tipo,año,ncodi
1087,1087,0.0,0.0,0.0,0.0,0.0,consulExter,2013,"266,00"
26218,26218,36864.0,468061.0,22349.0,445712.0,134099.0,Urgencia,2010,"918,00"
26112,26112,26388.0,69076.0,29765.0,39311.0,58077.0,Urgencia,2010,"993,00"
37794,37794,0.0,0.0,0.0,0.0,0.0,consulExter,2020,883
36923,36923,1043312.0,29005430.0,28760323.0,245107.0,251037.0,Hospital,2020,921
5080,5080,26972.0,293607.0,173980.0,119627.0,38715.0,Hospital,2014,"846,00"
50086,50086,0.0,0.0,0.0,0.0,0.0,hospDom,2011,"302,00"
45602,45602,0.0,0.0,0.0,0.0,0.0,hospDom,2018,174
53596,53596,114.0,0.0,0.0,0.0,457.0,hospDia,2016,849
6170,6170,4150.0,0.0,0.0,0.0,0.0,CMA,2014,"663,00"